[package]
name = "blogelf"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
include_dir = "0.7.3"
markdown = "1.0.0-alpha.17"
toml = "0.8.13"
serde = { version = "1.0", features = ["derive"] }
