src_dir = "./src"
blog_tmpl = "./templates/blog.html"
index_tmpl = "./templates/index.html"

index_build = "./index.html"
build_dir = "./build"

[globals] # global variables
name = ${name}
default_author = ${name}
